## Session 4 - 8 Mar 2022
LWirjowerdojo - PYTN071ONL010

## Numpy - Numerical Python
- Related to numbers (to process numbers)

In [3]:
import numpy as np

### Array - Structured Data
- contains numbers
- string is not suitable (if it contains string, use LIST instead)
- CRUD: Create Read Update Delete (everytime we encounter a new data)
    - np.array([]) # array that contains the number within the []
    - np.zeros(10) # create numpy array contains 0 with size: 10
    - np.ones(5) # contains 1 size: 5
    - np.empty(7) # empty array with size: 7
    - np.arange(5) # create an array that contains numbers from 0-4
        - np.arange(5,10) # result: 5,6,7,8,9
        - np.arange(10,100,25) # result: 10, 35, 60, 85
    - np.random.random(15) # random numbers with size: 15; range of values: 0-1
- for 2D array: row starts from index 0, column starts from index 1
    

#### Create

In [8]:
# example
a= np.array([1,2,3])
print(a)
print(type(a)) # nd array - n dimensional array

[1 2 3]
<class 'numpy.ndarray'>


In [15]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [192]:
np.empty((1,3))

array([[0.e+000, 1.e-323, 2.e-323]])

In [193]:
np.arange(5,11).reshape((2,3))

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
# if within the same script it contains the same array size, it will output the same numbers (applies to ones and random)
np.empty(7)

array([4.66505774e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.16202013e-322])

In [17]:
print(np.arange(5)) # numbers from 0 to anything -1 within the bracket
print(np.arange(5,10)) # numbers from 5 - 9
print(np.arange(5,10,2)) # numbers from 5 with 2 inc up to <10

[0 1 2 3 4]
[5 6 7 8 9]
[5 7 9]


In [194]:
c=np.random.random(10)
print(c)
np.random.random(10).reshape((5,2))

[0.13255935 0.11742796 0.45280427 0.99623131 0.80299879 0.23568154
 0.46423287 0.85392374 0.72751237 0.72329157]


array([[0.16224688, 0.13489967],
       [0.17273654, 0.04675615],
       [0.7664776 , 0.71930678],
       [0.1179199 , 0.39280905],
       [0.9329625 , 0.22860125]])

In [28]:
d=c*6
print(d)

[3.57138356 3.93694835 5.01895944 1.64922593 1.5427855  1.6106932
 4.57928952 0.249463   4.43128591 3.67413309]


In [29]:
# converting it to an integer
d.astype(int)

array([3, 3, 5, 1, 1, 1, 4, 0, 4, 3])

#### Read
- assume that arr is a numpy array
- the following items are PROPERTY of the shape (not a function), no need for the () after
- arr.shape - to check the shape of the array (column & row)
- arr.size - no of numbers within the array
- arr.ndim - matrix "size"

In [37]:
arr=np.array([[2,5,7,9,0]]) # with the two brackets, it indicates that it contains a specific number of row

In [39]:
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[2 5 7 9 0]]
(1, 5)
5
2


In [40]:
arr=np.array([[2,5,7,9,0], [21,15,17,91,10]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 2  5  7  9  0]
 [21 15 17 91 10]]
(2, 5)
10
2


In [42]:
# total numbers within the >1 nd array must be the same, otherwise it will not work as a regular numpy array (warning/complain will pop up)
# empty data can be replaced with np.NAN
arr=np.array([[2,5,7,9,np.NAN], [21,15,17,91,10]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]
(2, 5)
10
2


In [79]:
# indexing: to read based on index
print(arr)
print(arr[0,1], "take the first row and second column")

# slicing: to take few items within the array
print(arr[:,1:3], "take the first and second row (denoted by the :) and the first and second column")

[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]
5.0 take the first row and second column
[[ 5.  7.]
 [15. 17.]] take the first and second row (denoted by the :) and the first and second column


#### Update 
Edit numpy array
- np.append() - append 2 numpy array into 1
- np.delete() - delete based on index
- np.sort() - sort items from smallest to largest value

#### Reshape

In [50]:
print(arr)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]


In [51]:
print(arr.shape)

(2, 5)


In [55]:
arr2=arr.reshape((10,)) # reshape must be referenced to the number of values that exist within the numpy array
print(arr2)
print(arr2.shape)

[ 2.  5.  7.  9. nan 21. 15. 17. 91. 10.]
(10,)


In [56]:
# reshape to 2D
arr2=arr.reshape((5,2)) # 5 rows, two columns
print(arr2)
print(arr2.shape)

[[ 2.  5.]
 [ 7.  9.]
 [nan 21.]
 [15. 17.]
 [91. 10.]]
(5, 2)


In [57]:
arr2=arr.reshape((5,2,1)) # 3D
print(arr2)
print(arr2.shape)

[[[ 2.]
  [ 5.]]

 [[ 7.]
  [ 9.]]

 [[nan]
  [21.]]

 [[15.]
  [17.]]

 [[91.]
  [10.]]]
(5, 2, 1)


#### Append

In [59]:
np.append(arr,[5])

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  5.])

In [60]:
arr

array([[ 2.,  5.,  7.,  9., nan],
       [21., 15., 17., 91., 10.]])

In [61]:
np.append(arr, [[5,10,75], [10,11,12]])

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  5., 10., 75.,
       10., 11., 12.])

In [62]:
np.append(arr,np.ones(3))

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  1.,  1.,  1.])

In [67]:
np.append(arr, [[1,2,3,4,5]], axis=0) # the array will be appended on a new row (axis 0 represents a new row)

array([[ 2.,  5.,  7.,  9., nan],
       [21., 15., 17., 91., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [69]:
np.append(arr, [[1], [2]], axis=1) # axis 1 represents a new column

array([[ 2.,  5.,  7.,  9., nan,  1.],
       [21., 15., 17., 91., 10.,  2.]])

#### Delete

In [70]:
print(arr)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]


In [74]:
# delete value=9
# located on the first row (0) and 4th column
np.delete(arr,4,1) # deleting the fourth column 

array([[ 2.,  5.,  7.,  9.],
       [21., 15., 17., 91.]])

#### Sort
- sort from small to large

In [78]:
arr[0,3]=90
print(arr)
print(np.sort(arr))

[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]
[[ 2.  5.  7. 90. nan]
 [10. 15. 17. 21. 91.]]


In [77]:
print(arr)

[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]


#### Additional techniques:
- change np.array from 1D to 2D
    - newaxis
    - expand_dims

In [80]:
arr2=np.array([9,12,67,-5])
print(arr2)

[ 9 12 67 -5]


In [81]:
print(arr2[np.newaxis]) # creating a new axis, do highlight on the extra [ ] 

[[ 9 12 67 -5]]


In [83]:
a3=(arr2[:,np.newaxis]) # creating a new axis, do highlight on the extra [ ] 
print(a3)
print(a3.shape)

[[ 9]
 [12]
 [67]
 [-5]]
(4, 1)


In [86]:
a3=np.expand_dims(arr2, axis=0) # add the new dimension to the 0 axis (new row)
print(a3)
print(a3.shape)

[[ 9 12 67 -5]]
(1, 4)


In [85]:
a3=np.expand_dims(arr2, axis=1) # add the new dimension to the 0 axis (new column)
print(a3)
print(a3.shape)

[[ 9]
 [12]
 [67]
 [-5]]
(4, 1)


In [89]:
# from kode.id
a=np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##### Indexing with condition, Slicing, Query

In [96]:
arr2=np.arange(100,400,25)
print(arr2)
print(arr2.size)
arr2=arr2.reshape((3,4))

[100 125 150 175 200 225 250 275 300 325 350 375]
12


In [97]:
arr2

array([[100, 125, 150, 175],
       [200, 225, 250, 275],
       [300, 325, 350, 375]])

In [98]:
# Indexing - taking the 250; 3D array: second row (index=1) and third column (index=2)
arr2[1,2]

250

In [100]:
# Slicing - taking 250 275 350 375; 3D array: second and third row (index=1 and 2), third and fourth column (index: 2 and 3 respectively)
arr2[1:3, 2:4]

array([[250, 275],
       [350, 375]])

In [101]:
# Slicing - taking 250 275 350 375
arr2[1:, 2:] # if it's the last number, we may neglect the indices

array([[250, 275],
       [350, 375]])

In [102]:
# Slicing - taking 250 275 350 375 (other ways)
arr2[-2:,-2:]

array([[250, 275],
       [350, 375]])

In [106]:
# Query - divisible by 2
genap=arr2%2==0 
print(genap)
print(arr2)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[[100 125 150 175]
 [200 225 250 275]
 [300 325 350 375]]


In [107]:
# Query - anything >200
diatas200=arr2>200
print(diatas200)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [108]:
print(genap & diatas200)

[[False False False False]
 [False False  True False]
 [ True False  True False]]


In [109]:
arr2[genap & diatas200]

array([250, 300, 350])

In [114]:
arr2[(arr2%2==0) & (arr2>200)] # conditions may be included directly

array([250, 300, 350])

In [128]:
# Query on arr - even values
print(arr)
arr[arr%2==0]
# invalid value encountered as the arr contains NAN value

[[ 2.  5.  7. 90. -3.]
 [21. 15. 17. 91. 10.]]


array([ 2., 90., 10.])

In [126]:
arr[0,4]=(-3)
print(arr)
arr[arr%2==0]

[[ 2.  5.  7. 90. -3.]
 [21. 15. 17. 91. 10.]]


array([ 2., 90., 10.])

#### Stack, split and copy
- stack
    - vstack - vertical
    - hstack - horizontal
- split
    - vsplit - top, mid, bottom
    - hsplit - left mid, right
- copy
    - view by reference
    - copy by value - deep copy

In [127]:
arr

array([[ 2.,  5.,  7., 90., -3.],
       [21., 15., 17., 91., 10.]])

In [145]:
a=np.array([[2,5,7,9,np.NAN], [21,15,17,91,10]])
print(a)
print(a.shape) # 2 rows 5 columns

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]
(2, 5)


In [141]:
arr=np.array([[2,5,7,9,-3], [21,15,17,91,10]])
print(arr)

[[ 2  5  7  9 -3]
 [21 15 17 91 10]]


In [142]:
np.vstack((a,arr))

array([[ 2.,  5.,  7.,  9., nan],
       [21., 15., 17., 91., 10.],
       [ 2.,  5.,  7.,  9., -3.],
       [21., 15., 17., 91., 10.]])

In [4]:
b = np.array([[3,4],[5,6]])
print(b.shape)

(2, 2)


In [146]:
# hstack - rows MUST match
np.hstack((a,b))

array([[ 2.,  5.,  7.,  9., nan,  3.,  4.],
       [21., 15., 17., 91., 10.,  5.,  6.]])

In [147]:
np.hstack((a,b,a,b))

array([[ 2.,  5.,  7.,  9., nan,  3.,  4.,  2.,  5.,  7.,  9., nan,  3.,
         4.],
       [21., 15., 17., 91., 10.,  5.,  6., 21., 15., 17., 91., 10.,  5.,
         6.]])

In [148]:
np.vsplit(a,2)

[array([[ 2.,  5.,  7.,  9., nan]]), array([[21., 15., 17., 91., 10.]])]

In [149]:
result=np.vsplit(a,2)

In [151]:
print(result)
print(type(result))

[array([[ 2.,  5.,  7.,  9., nan]]), array([[21., 15., 17., 91., 10.]])]
<class 'list'>


In [163]:
# vertical split - 2 arrays; a1 and a2 respectively
# as a array is 2x1 type of array, vsplit can only be done by 2
a1,a2=np.vsplit(a,2)
print(a1, type(a1))
print(a2, type(a2))

[[ 2.  5.  7.  9. nan]] <class 'numpy.ndarray'>
[[21. 15. 17. 91. 10.]] <class 'numpy.ndarray'>


In [169]:
b=np.arange(12).reshape((3,4))
print(b)
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [162]:
print(b.shape) # shape is 3x4 array, hence vsplit can be done for 3
b1,b2,b3=np.vsplit(b,3)
print(b1,b2,b3)

# not possible to be split into 2, as it contains 3 rows

(3, 4)
[[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]


In [167]:
# hsplit
# 2 columns
print(b)
b21, b22=np.hsplit(b,2)
print(b21,b22)
# 4 columns
b41,b42,b43,b44=np.hsplit(b,4)
print(b41,b42,b43,b44)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]] [[ 2  3]
 [ 6  7]
 [10 11]]
[[0]
 [4]
 [8]] [[1]
 [5]
 [9]] [[ 2]
 [ 6]
 [10]] [[ 3]
 [ 7]
 [11]]


In [16]:
# copy
print(b)
b_copy=b.copy()
b_copy[0,1]=100
print(b_copy)
print(b) # b array remains

[[  3 100]
 [  5   6]]
[[  3 100]
 [  5   6]]
[[  3 100]
 [  5   6]]


In [17]:
# copy
print(b)
b_view=b.view()
b[1,1]=25 
print(b_view) # as this has been changed, b_view also changes

[[  3 100]
 [  5   6]]
[[  3 100]
 [  5  25]]


b and b_view are the same array with two different names

In [238]:
b_copy=b.copy()
print(b_copy)

[[ 7  8]
 [ 9 10]
 [11 12]]


b and b_copy are two different arrays

#### Basic array operation
- manipulate number within the numpy array using mathematical operations and number

In [172]:
score=[60,78,99,43]
# add 1 point to all
score_arr=np.array(score) # must be defined as numpy array - counts as concatenate
score_arr+1

array([ 61,  79, 100,  44])

In [173]:
np.array([60,78,99,43]) + [10,10,1,10]

array([ 70,  88, 100,  53])

#### can use other mathematical operations \+ \- \/ \* \% \**

In [175]:
np.arange(5) + 5 * 3 / 2

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [176]:
np.arange(5) + np.ones(5) * 8

array([ 8.,  9., 10., 11., 12.])

In [177]:
np.arange(5) % 2

array([0, 1, 0, 1, 0])

Other functions include: min, max, sum, mean, standard deviation, corr coefficient

In [178]:
print(a)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]


In [185]:
arr[0,3]=90
print(arr)

[[ 2  5  7 90 -3]
 [21 15 17 91 10]]


In [186]:
print(arr.max())

91


In [187]:
# look per axis
print(arr.max(axis=0))

[21 15 17 91 10]


In [188]:
print(arr.max(axis=1))

[90 91]


In [189]:
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

-3
[ 2  5  7 90 -3]
[-3 10]


In [190]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

255
[ 23  20  24 181   7]
[101 154]


In [191]:
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

25.5
[11.5 10.  12.  90.5  3.5]
[20.2 30.8]


### Matrices
2D numpy array (no of column will be the same on every rows), contains numbers

1 column matrix is called *vector*

In [195]:
print(np.array([[-2,5,6],[5,2,7]]))

[[-2  5  6]
 [ 5  2  7]]


In [197]:
print(([[-2,5,6],[5,2,7]])) # different 

[[-2, 5, 6], [5, 2, 7]]


#### Dot product - matrices multiplication (math)

In [198]:
# multiplication of 2 numpy array: multiply two values of the same location
np.array([1,2]) * np.array([5,6])

array([ 5, 12])

In [209]:
a=np.arange(1,7).reshape((2,3))
print(a)
b=np.arange(7,13).reshape((3,2))
print(b)
print(a.dot(b))

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


Example on why we have to do this:
- Bakery sells 3 types of pies at different prices: apple (3), cherry (4), blueberry (2)
- Sold different amount on each day (Mon-Thu)

In [210]:
sells=np.array([[13,9,7,15],[8,7,4,6],[6,4,0,3]])
price=np.array([3,4,2]) # contains 1 column, 3 rows; matrix size 1 x 3

# dot follows mathematical matrices rules where the shape MATTERS
# in this case price 1x3, sells 3x4, hence shape result becomes (1x3) . (3x4) = (1x4)
print(sells.shape)
print(price.shape)
total=price.dot(sells)
print(total)
print(total.shape)
print("grand total: $", total.sum())

(3, 4)
(3,)
[83 63 37 75]
(4,)
grand total: $ 258


#### Transpose

In [213]:
print(sells)
print(sells.shape)

[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]
(3, 4)


In [214]:
print(sells.T) # transposed matrix becomes 4 x 3

[[13  8  6]
 [ 9  7  4]
 [ 7  4  0]
 [15  6  3]]


In [216]:
sellstr=sells.T
print(sellstr)
print(sellstr.shape)

[[13  8  6]
 [ 9  7  4]
 [ 7  4  0]
 [15  6  3]]
(4, 3)


In [217]:
# other way to transpos matrix
sells.transpose()

array([[13,  8,  6],
       [ 9,  7,  4],
       [ 7,  4,  0],
       [15,  6,  3]])

N-Dimensional array 

In [219]:
np.arange(100).reshape((4,5,5)) # 3D, values from 0-99, 4 parts, 5 rows, 5 columns each

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [221]:
np.arange(60).reshape((2,5,3,2)) # 4D, 0-59, 2 parts, each have 5 parts that contains 3 rows 2 columns

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]]],


       [[[30, 31],
         [32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

Flatten-Dimensional array
to change numpy array to 1D
- flatten (by value, similar to copy)
- ravel (by reference, similar to view)

In [226]:
arr3d=np.arange(30).reshape((2,5,3))
arr3d_flat=arr3d.flatten()
arr3d_ravel=arr3d.ravel()

print(arr3d_flat)
print(arr3d_ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [230]:
arr3d_ravel[0]=500 # change the value(s)

In [228]:
print(arr3d_ravel)

[500   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


In [229]:
print(arr3d) 

[[[500   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]]


In [232]:
arr3d_flat[0]=150
print(arr3d_flat)

[150   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


In [234]:
print(arr3d) # arr3d remains the same as the ravel

[[[500   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]]


References: https://www.w3schools.com/python/

Tips:
- 1D numpy array -> transposed to 2D (to vector)

Most common:
- np.array
- np.random.random
- shape
- reshape
- mathematical operations
- aggregate
- indexing & slicing
- transpose

#### Practice:
Create a 2D numpy array 5x6 (5 rows, 6 columns):
- use np.array, np.zeros, np.arange
- use indexing and slicing to take 1 value and few values from the newly created numpy array
    - number on first row, column 3
    - numbers from row: 2-4 and last column
- dot product: np.array([5,4,6,7,8])

In [50]:
practice1=np.arange(6).reshape(1,6)
practice2=np.zeros(6).reshape((1,6))
practice3=np.random.random(6).reshape(1,6)
practice4=np.array([6,9,12,14,0,5]).reshape(1,6)
practice5=np.ones((1,6))

#result=np.empty([])

print(practice1)
print(practice2)
print(practice3)
result=np.append(practice1,practice2,axis=0)
print(result)

[[0 1 2 3 4 5]]
[[0. 0. 0. 0. 0. 0.]]
[[0.33740997 0.96058773 0.16051011 0.67436022 0.61063154 0.65629696]]
[[0. 1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0. 0.]]


In [51]:
result=np.append(result,practice3,axis=0)
print(result)
print(result.shape)

[[0.         1.         2.         3.         4.         5.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.33740997 0.96058773 0.16051011 0.67436022 0.61063154 0.65629696]]
(3, 6)


In [52]:
result=np.append(result,practice4,axis=0)
result=np.append(result,practice5,axis=0)
print(result)
print(result.shape)

[[ 0.          1.          2.          3.          4.          5.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.33740997  0.96058773  0.16051011  0.67436022  0.61063154  0.65629696]
 [ 6.          9.         12.         14.          0.          5.        ]
 [ 1.          1.          1.          1.          1.          1.        ]]
(5, 6)


In [56]:
# - use indexing and slicing to take 1 value and few values from the newly created numpy array
print(result[0,2]) # number on first row, column 3
print(result[1:4,5]) # numbers from row: 2-4 and last column

2.0
[0.         0.65629696 5.        ]


In [77]:
new=np.arange(30).reshape(6,5)
print(new)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [79]:
new=new.reshape(5,6)
print(new)
new[3]=np.zeros(6)
print(new)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  0  0  0  0  0]
 [24 25 26 27 28 29]]


In [82]:
print(new[0,2]) # number on first row, column 3
print(new[1:4,5]) # numbers from row: 2-4 and last column

2
[11 17  0]
